### ISSUE TITLE
Build error while using sudo make

### ISSUE THREAD

**Issue by racterub** [leetonidas/demovfuscator#10] opened 2018-05-03 22:40 UTC
Compiled on Ubuntu-16-04(vagrant)
I don't know is this only happen on my side :(

![image](https://user-images.githubusercontent.com/20561837/39606081-11fbc402-4f66-11e8-922a-3a62a79d1621.png)

Thanks!

**Comment by leetonidas** [comment] 2018-05-03 23:02
You mentioned in the other issue #9 that you compiled z3 from source. Are you using recent sources from github? I think the problem is their commit https://github.com/Z3Prover/z3/commit/16a2ad9afd8bed86fc7d5d2f40ca3d48b7fedd07 which switched from internal definitions to stdint.h.

**Comment by racterub** [comment] 2018-05-04 00:12
Yes, I just compiled yesterday :p
I will try to change version to recompile it again

Thanks!

- Racter

On May 4, 2018, at 7:02 AM, leetonidas <notifications@github.com<mailto:notifications@github.com>> wrote:


You mentioned in the other issue #9<https://github.com/kirschju/demovfuscator/issues/9> that you compiled z3 from source. Are you using recent sources from github? I think the problem is their commit https://github.com/Z3Prover/z3/commits/16a2ad9afd8bed86fc7d5d2f40ca3d48b7fedd07 which switched from internal definitions to stdint.h.

**Comment by racterub** [comment] 2018-05-04 17:45
@leetonidas Comfirmed it's Z3Prover/z3@16a2ad9 issue.

Build success

**Comment by leetonidas** [comment] 2018-05-05 13:33
I will update this once it is rolled out more broadly. I close this issue for now.

**Closed as completed by leetonidas** 2018-05-05 13:33 UTC
